
spring:
  application:
    name: javayh-redis
  datasource:
    url: jdbc:mysql://localhost:3306/rabbitmq?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    database: 0
    password: