
server:
  port: 8002
  servlet:
    context-path: /
## consumer配置
## springboot整合rabbitmq的基本配置
spring:
  application:
    name: kafka-consumer
  datasource:
    url: jdbc:mysql://localhost:3306/rabbitmq?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  redis:
    database: 0
    port: 6379
    host: 127.0.0.1
    password:
mybatis:
  type-aliases-package: com.javayh.common.entity
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰命名,l_name -> lName
    jdbc-type-for-null: NULL
    lazy-loading-enabled: true
    aggressive-lazy-loading: true
    cache-enabled: true #开启二级缓存
    call-setters-on-nulls: true #map空列不显示问题
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.javayh.dao: DEBUG