server:
  port: 8001
## producer配置
spring:
  application:
    name: kafka-producer

  datasource:
    url: jdbc:mysql://localhost:3306/rabbitmq?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
mybatis:
  type-aliases-package: com.javayh.common.entity
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰命名,l_name -> lName
    jdbc-type-for-null: NULL
    lazy-loading-enabled: true
    aggressive-lazy-loading: true
    cache-enabled: true #开启二级缓存
    call-setters-on-nulls: true #map空列不显示问题
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.javayh.dao: DEBUG